POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

os_type=$(uname -s)

# ssh agent
echo "starting ssh-agent"
eval `ssh-agent -s`

echo "adding keys"
ssh-add ~/.ssh/id_rsa > /dev/null

echo "keys added:"
ssh-add -l

export PATH=$PATH:/etc/profiles/per-user/diego/bin

# customizations for macos
if [[ "$os_type" == "Darwin" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export PATH=$PATH:/Applications/Docker.app/Contents/Resources/bin:/Users/diego/bin:/run/current-system/sw/bin

    export NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs:/nix/var/nix/profiles/per-user/root/channels
else
    export PATH=$PATH:/home/diego/bin
fi
